# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-30 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=30)),
                ('product_name', models.CharField(max_length=30)),
                ('image_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('review', models.CharField(max_length=3000)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('overall', models.CharField(choices=[('POS', 'Positive'), ('NEG', 'Negative'), ('NEU', 'Neutral')], max_length=3, null=True)),
                ('camera', models.CharField(choices=[('POS', 'Positive'), ('NEG', 'Negative'), ('NEU', 'Neutral')], max_length=3, null=True)),
                ('performance', models.CharField(choices=[('POS', 'Positive'), ('NEG', 'Negative'), ('NEU', 'Neutral')], max_length=3, null=True)),
                ('battery', models.CharField(choices=[('POS', 'Positive'), ('NEG', 'Negative'), ('NEU', 'Neutral')], max_length=3, null=True)),
                ('display', models.CharField(choices=[('POS', 'Positive'), ('NEG', 'Negative'), ('NEU', 'Neutral')], max_length=3, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Products')),
            ],
        ),
    ]
