# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-01 17:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='brand_name',
        ),
        migrations.AddField(
            model_name='reviews',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='reviews',
            name='email',
            field=models.EmailField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='rivals',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(max_length=50),
        ),
    ]
