# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-01 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_auto_20160501_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image_name',
            field=models.CharField(max_length=100),
        ),
    ]
